### ISSUE TITLE
Freehand draw doesn't work in Safari with trackpad (?)

### ISSUE THREAD

**Issue by gloriafang123** [edemaine/cocreate#89] opened 2020-09-01 22:07 UTC
Would it be possible to support Safari? Several tools (freehand, drag, shapes) don't seem to work. Thank you!

**Comment by diomidov** [comment] 2020-09-01 22:26
It works fine for me in Safari... What version are you using?18:08, September 1, 2020, gloriafang123 <notifications@github.com>:
Would it be possible to support Safari? Several tools (freehand, drag, shapes) don't seem to work. Thank you!

**Comment by edemaine** [comment] 2020-09-01 22:39
I just tested on

* Safari 13.1.2 on Catalina
* Safari 12.1.2 on Mohave
* Safari 11.1.2 on High Sierra
* Safari 10.1.2 on Sierra

and all the features you mentioned seem to work fine.  Can you elaborate on what you mean by "don't seem to work"?

I had to go all the way back to Safari 9.1.3 on El Capitan to get Cocreate not to work. But that didn't work at all -- no tools displayed, page number remained `?`, etc. So I'm guessing you're not that far back.

**Comment by gloriafang123** [comment] 2020-09-01 23:09
I'm using Safari 12.1.2 on OS Sierra 10.12.6 on MacBook Pro (2017, with the force trackpad - perhaps trackpad issue?). 

Luckily it works for me on Chrome. Just wanted to be sure for recitation tomorrow in case any students are stuck too (though it seems like it's just me). Sorry for the trouble!

**Comment by edemaine** [comment] 2020-09-01 23:11
Trackpad is a good guess.  I don't have a Macbook Pro (or any Mac laptop) so can't test.  Do you have an external mouse you could test, to help isolate the problem?  Do you get the sense that the page is scrolling or selecting instead of the intended drawing?

But definitely a good idea to recommend Chrome to your students.  It's what I test all my tools in, almost exclusively, so they're likely to get the best results with it.

**Comment by edemaine** [comment] 2020-09-17 13:54
FYI, Safari 14 was just released, though I'm guessing you can't install it without upgrading to High Sierra or Catalina.

I'm going to close this issue, as I can't reproduce and supporting old Safari versions probably shouldn't be a priority, alas. Let me know if you have any more data (e.g. from testing with an external mouse) and we can revisit.

**Closed by edemaine** 2020-09-17 13:54 UTC
