### ISSUE TITLE
Rectangle select not working with Firefox 83.0

### ISSUE THREAD

**Issue by dpl** [edemaine/cocreate#133] opened 2020-12-06 23:00 UTC
Anchoring the first corner works, but then the second corner is never confirmed, all that happens is forever dragging around the second corner. Have to select another mode/tool in order to escape that behavior

**Comment by edemaine** [comment] 2020-12-07 00:13
Duplicate of #87. Please use Chrome in the meantime -- sorry.

**Closed by edemaine** 2020-12-07 00:14 UTC
